baseURL = 'https://NicknEma.github.io/'
languageCode = 'en-us'
title = 'Answers at the End'
theme = "vans"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
[params]
  subtitle = 'Me thinks. Me writes. Me shares.'
  math = true