name = "Vans"
license = "MIT"
licenselink = "https://github.com/serkodev/holy/blob/master/LICENSE"
description = "Theme for the Answers at the End website. Based on the Holy theme by SerkoDev."
homepage = "https://nicknema.github.io"
demosite = "https://nicknema.github.io"
tags = ["blog", "responsive", "simple", "minimal", "personal", "dark", "dark mode", "contact"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41.0"

[author]
  name = "NicknEma"
  homepage = "https://nicknema.github.io"
